[package]
name = "benchmarking"
version = "0.1.0"
authors = ["Eduard Urbach <e.urbach@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
